# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ios-challenge' do

pod 'objectiveflickr'
pod 'AFNetworking', '~> 2.0'
pod 'Mantle'
pod 'MBProgressHUD'

end

target 'ios-challengeTests' do

end

